name: Deploy Next.js to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: 34.221.34.171
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /var/www/nextapp
          strip_components: 1
          recursive: true

      - name: Run build & start app via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 34.221.34.171
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nextapp
            npm install
            npm run build
            npx pm2 delete sedeer-app || true
            npx pm2 start npm --name "sedeer-app" -- start
            npx pm2 save
            npx pm2 list

